### ISSUE TITLE
Is the blobID uuid?

### ISSUE THREAD

**Issue by shashwat-kalpvaig** [noelmartinon/odk_images#1]
I am having uuid for each submission file and filename. So is it the uuid that have been used 

I am using as the following image url

/index.php?blobId=uuid:d4e35c05-322c-4ba7-9d28-37a9efdfffa7&photo=Screenshot_2021-11-21-20-53-12-00_930ee7d2985167ff9456b472c4028ebe-20_53_21.jpg

**Comment by 50shashwat** [comment]
Got it. Its the Project ID.

**Comment by shashwat-kalpvaig** [comment]
Currently its only taking in the blobID and any random name doesn;t change the query output. I am using ODK Central oData API. Where could i find the blobID in there?

**Comment by noelmartinon** [comment]
I update the README.md. Does this give you the answer?
